<?php
/**
 * Created by PhpStorm.
 * User: Djon
 * Date: 14.01.2017
 * Time: 17:22
 */

namespace app\models;
use yii\db\ActiveRecord;


class Category extends ActiveRecord
{
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    public static function tableName(){
        return 'category'; // TODO: Change the autogenerated stub
    }
    public function getProducts(){
        return $this->hasMany(Product::class, ['category_id' => 'id']);

    }
}