<?php
/**
 * Created by PhpStorm.
 * User: Djon
 * Date: 14.01.2017
 * Time: 17:54
 */

namespace app\models;
use yii\db\ActiveRecord;


class Product extends ActiveRecord
{
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    public static function tableName(){
        return 'product'; // TODO: Change the autogenerated stub
    }
    public function getCategory(){
        return $this->hasOne(Category::class, ['id' => 'category_id']);

    }
}